version: '3.3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - './tmp:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=212121
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    links:
      - postgres
